@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.somber.suscraft.block.susitefurnace;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;